version: '3'
services:
  app:
    container_name: app
    build: .
    networks:
      - network
    depends_on:
      datastore:
        condition: service_started
    environment:
      DATABASE_HOST: datastore
  datastore:
    container_name: datastore
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: price-tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

volumes:
  pgdata:

networks:
  network: