apiVersion: batch/v1
kind: CronJob
metadata:
  name: price-track-cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: price-track
            image: price-tracker-app:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_HOST
                value: "host.docker.internal"
          restartPolicy: OnFailure